#!/bin/sh

default_cmd='clear; node main.js'
default_ext='js,css,html,json'

extarg=$default_ext
if [ -n "$1" ]; then
	extarg=$1
fi
extargs=`echo $extarg | tr , ' '`
extentions=''
for ext in $extargs; do
	if [ -z "$extentions" ]; then
		extentions="-name '*.$ext'"
	else
		extentions=$extentions" -o -name '*.$ext'"
	fi
done

if [ -n "$1" ]; then
	echo here
	shift
fi

cleanup() {
	rm -f "$timestamp_file"
	exit
}

timestamp_file=$(mktemp)
trap 'cleanup' 2
touch "$timestamp_file"

cpid=''
found='first'
while true; do
	sleep .2
	if [ -n "$found" ]; then
		if [ -n "$cpid" ]; then
			kill $cpid
			wait $cpid
		fi
		if [ -n "$1" ]; then
			sh -c "$1" &
			cpid=$!
		else
			sh -c "$default_cmd" &
			cpid=$!
		fi
	fi
	found=`eval 'find \( '$extentions' \) -type f -newer '"$timestamp_file"' -print'`
	touch "$timestamp_file"
done


